// let btn = document.querySelector(".btn");


function criarLorem() {
    let concat = '';
    let paragraphNumber = document.querySelector("#count").value;

    if(paragraphNumber >= 1) {
        let lorem = text.slice(0, paragraphNumber);
        lorem.forEach(paragraph => {
            concat = concat + '<br><br>' + paragraph;
        });
        document.querySelector("#word").innerHTML = concat;
    }
    else {
        let lorem= text.slice(0,Math.floor(Math.random() * 10));
        lorem.forEach(paragraph => {
            concat = concat + '<br><br>' + paragraph;
        });
        document.querySelector("#word").innerHTML = concat;
    }
}

const text = [
'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis et ultrices tortor. Ut ut sodales felis, in tincidunt lectus. Duis eu elit eu dui laoreet dapibus. Nunc pretium at est sagittis dignissim. Nunc sed lacus vulputate, scelerisque libero quis, ultrices lorem. Phasellus luctus neque ut sagittis molestie. Nullam eget condimentum eros. Praesent in iaculis eros. Aenean eu turpis nibh. Sed eu viverra magna, mattis pellentesque erat. Vestibulum quis turpis nec dolor iaculis euismod. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris suscipit quis orci eget maximus.',
'Suspendisse sit amet magna ac sem dapibus vulputate quis in erat. Duis ullamcorper enim id purus rhoncus, vel imperdiet neque ullamcorper. In tincidunt ut urna at aliquam. Maecenas eu nisi rhoncus, semper ligula sit amet, semper purus. Integer interdum blandit facilisis. Nunc tincidunt risus ac sapien hendrerit mattis. Quisque congue diam accumsan nulla ullamcorper, elementum hendrerit quam molestie. In non massa sit amet nunc tempus bibendum ornare non est. Proin congue ut arcu vitae rutrum. Donec dui nibh, porttitor a ipsum ac, tincidunt varius enim.',
'Vestibulum leo metus, hendrerit cursus elementum sed, pretium efficitur urna. Suspendisse consequat consequat turpis ut vehicula. Vestibulum cursus orci sit amet metus accumsan, nec porta lacus sollicitudin. Donec quis porttitor nisl, sed imperdiet quam. Maecenas a mattis elit. Phasellus non nulla quis purus finibus accumsan. Integer at ullamcorper sem. Morbi quis imperdiet elit, eu venenatis nisi. Sed sem ante, bibendum id placerat nec, dignissim in nunc. Fusce sed eleifend sem, nec interdum massa. Cras sed semper lectus, non tempus purus. Duis eleifend tortor sit amet libero maximus, id imperdiet odio cursus. Donec nec neque malesuada, rutrum nisi et, placerat velit. Quisque quis pulvinar quam. Aenean convallis scelerisque placerat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
'Donec mollis dapibus maximus. Fusce augue lorem, volutpat quis mollis vitae, lobortis gravida ex. Cras et metus mauris. Quisque venenatis sem at sapien pellentesque tincidunt. Pellentesque dictum odio condimentum massa interdum auctor. Curabitur accumsan dapibus libero vitae ornare. Quisque sagittis diam tempus mollis eleifend. Suspendisse non malesuada nibh, non rhoncus mi. Nunc molestie orci eros, cursus pharetra lorem aliquam sed. Phasellus malesuada neque eros, vitae finibus arcu iaculis et. Nullam imperdiet lacus metus, quis tincidunt est consectetur quis. In ut augue tellus. Donec at finibus velit. Nam congue, dui sed rhoncus viverra, mauris ligula ornare ligula, non tincidunt dolor diam aliquet quam. Nunc sagittis erat arcu, ut auctor turpis porta nec.',
'Vestibulum sit amet pulvinar mi. Quisque pharetra finibus consectetur. Mauris scelerisque tincidunt varius. Vestibulum facilisis massa sed est faucibus, ut iaculis metus egestas. Morbi semper, purus vitae luctus faucibus, velit mauris facilisis orci, vel ultrices quam mauris sit amet est. Mauris eu facilisis metus. Duis nec malesuada ligula. Aliquam erat volutpat. Vestibulum condimentum, orci quis lobortis hendrerit, sem est rhoncus urna, in tempus quam purus vitae leo. Sed non libero aliquet, convallis velit id, pretium lacus. Nullam ullamcorper iaculis quam ut finibus. Phasellus ut dapibus orci, quis luctus nisi. Praesent ex orci, elementum sit amet consequat sit amet, eleifend sed neque. Vestibulum vitae dictum tellus. Ut odio risus, pharetra eget dignissim quis, eleifend suscipit ex.',
'Vestibulum ac purus non ex consectetur interdum. Pellentesque risus mi, euismod vitae dui nec, lacinia euismod nunc. Fusce ac arcu a dolor pretium ultrices. In mollis ante a lectus consequat vehicula. Aliquam pulvinar, ante vitae tristique congue, lorem dui tristique odio, eu accumsan dolor diam a magna. Vivamus sed feugiat purus. In finibus luctus facilisis. Pellentesque dapibus magna lectus, sed pulvinar mi lacinia at. Morbi vestibulum tortor sed tempus commodo.',
'Duis turpis velit, venenatis in nulla quis, suscipit luctus lacus. Mauris augue magna, ornare vel mi eu, vehicula efficitur libero. Praesent accumsan diam nisl, a pellentesque nibh mattis vitae. Maecenas semper in erat vitae consectetur. Integer sit amet turpis pulvinar, vulputate mauris sit amet, vulputate erat. Morbi accumsan, ante eu accumsan fringilla, ante dui commodo neque, nec accumsan enim odio sit amet lorem. Duis mauris nibh, tincidunt sed ornare eu, aliquam eget justo. Sed faucibus non est dapibus vehicula. Sed finibus erat ligula, vel aliquet eros vulputate at. Aenean odio arcu, sollicitudin nec libero eget, porttitor eleifend eros. In feugiat lacus elit, ac consequat lorem rutrum quis. Cras orci mauris, aliquam sed semper in, elementum eu quam.',
'Vivamus molestie, sem nec vehicula pulvinar, tellus ex sodales magna, at commodo tellus risus sed felis. Phasellus tristique lectus eget nulla mattis, iaculis viverra nibh aliquet. Donec sed ipsum maximus velit viverra ornare. Aliquam erat volutpat. Donec urna nunc, viverra at convallis at, ornare id nisi. Pellentesque a placerat neque, vel scelerisque eros. Proin ultricies est interdum vulputate vehicula.',
'Proin tempus dapibus sem consectetur mattis. In cursus molestie molestie. Morbi lobortis dictum rutrum. Sed lacinia, diam mollis fringilla vestibulum, erat arcu hendrerit lectus, ut iaculis elit arcu a nunc. Maecenas consectetur ligula neque, dignissim fermentum ex placerat viverra. In porta sagittis elit et scelerisque. Aenean sit amet nisi felis. Nulla luctus metus lorem, at laoreet nibh blandit vel. Curabitur ultricies ligula eleifend urna scelerisque sodales. Aenean pharetra lorem mi, eu suscipit nisl accumsan eu. Curabitur commodo convallis purus et sagittis. Nullam et urna lectus. Maecenas quis mattis lorem, eu lobortis orci.',
'Etiam quis elit quis mauris lacinia venenatis eget eu purus. Curabitur varius laoreet condimentum. Sed suscipit lobortis dui a dignissim. Maecenas at diam vel nunc malesuada sagittis non sit amet eros. Nam dolor risus, malesuada congue ligula ut, semper cursus massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus nec nisl at lorem ullamcorper scelerisque. Duis sagittis quam et est euismod, id suscipit orci convallis. Aenean tempor leo mollis nunc viverra porta et nec orci. Fusce porttitor, tortor finibus consectetur sodales, ex lectus pulvinar mauris, sed iaculis felis sapien nec lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis a ultrices sapien, vel pellentesque enim. Maecenas sagittis euismod justo, ut viverra odio lacinia in. Etiam lacus tellus, cursus ac sagittis in, dictum non tortor. Proin at mauris id quam hendrerit suscipit at ut turpis. Nunc risus enim, malesuada eget gravida eget, gravida eget neque.'];
